languageCode:           "en"
title:                  "PaveJS"
baseURL:                "https://pavejs.org/"
enableInlineShortcodes: true

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404"]

module:
  mounts:
    - source: "node_modules/bootstrap-icons/icons"
      target: "static/svgs"

params:
  description:          "The best querying language in the world."
  authors:              "Casey Foster, Nathaniel Pendy"

  docs_version:         "1.0"
  repo:                 "https://github.com/caseywebdev/pave"
  npm:                  "https://npmjs.com/pave"