version: '2.1'

services:
  lb:
    image: nginx:1.19.7-alpine
    ports:
    - 80:80
    # - 443:443
    volumes:
    - ./src/nginx.dev.conf:/etc/nginx/nginx.conf
    - ./src/fullchain.pem:/etc/ssl/private/fullchain.pem
    - ./src/privkey.pem:/etc/ssl/private/privkey.pem
    networks:
      default:
        aliases:
        - dev.pavejs.org

  pavejsorg: &pavejsorg
    image: pavejs/pavejs.org-ci
    environment: &pavejsorg_environment
      VERSION: development
      WATCH: 1

  pavejsorg-build:
    <<: *pavejsorg
    command: ["true"]

  pavejsorg-livereload:
    <<: *pavejsorg
    command: ["true"]

  pavejsorg-test:
    <<: *pavejsorg
    command: ["true"]
    environment:
      <<: *pavejsorg_environment
      WEBSITE_URL: http://localhost