version: '2.1'

services:
  lb:
    image: nginx:1.19.7-alpine
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./src/nginx.conf:/etc/nginx/nginx.conf
    - ./src/fullchain.pem:/etc/ssl/private/fullchain.pem
    - ./src/privkey.pem:/etc/ssl/private/privkey.pem
    networks:
      default:
        aliases:
        - dev.pavejs.org

  web: &pavejsorg
    image: pavejs/pavejs.org-ci
    volumes:
      - ../pavejs.org/bin:/code/bin
      - ../pavejs.org/cogs.js:/code/cogs.js
      - ../pavejs.org/package-lock.json:/code/package-lock.json
      - ../pavejs.org/package.json:/code/package.json
      - ../pavejs.org/src:/code/src
      - dist:/code/dist
    build:
      args:
        VERSION: development
      context: ../pavejs.org
    environment: &pavejsorg_environment
      VERSION: development
      WATCH: 1

  build:
    <<: *pavejsorg
    command: ["true"]

  livereload:
    <<: *pavejsorg
    command: ["true"]

  test:
    <<: *pavejsorg
    command: ["true"]
    environment:
      <<: *pavejsorg_environment
      WEBSITE_URL: http://localhost

volumes:
  dist: