version: '3.9'

services:
  lb:
    image: nginx:1.19.7-alpine
    ports:
    - 80:80
    volumes:
    - ./src/nginx.conf:/etc/nginx/nginx.conf
    - ./src/fullchain.pem:/etc/ssl/private/fullchain.pem
    - ./src/privkey.pem:/etc/ssl/private/privkey.pem
    networks:
      default:
        aliases:
        - dev.pavejs.org

  web: &web
    volumes:
    - ./bin:/code/bin
    - ./cogs.js:/code/cogs.js
    - ./package-lock.json:/code/package-lock.json
    - ./package.json:/code/package.json
    - ./src:/code/src
    - dist:/code/dist
    build:
      args:
        VERSION: development
      context: ./
    environment:
      WEBSITE_URL: 'http://localhost'
      CACHE_CONTROL_MAX_AGE: 86400
      VERSION: development
      WATCH: 1

  build:
    <<: *web
    command: ["bin/build"]

  livereload:
    <<: *web
    command: ["bin/livereload"]

volumes:
  dist: