name: main
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: pavejs/pavejs.org-ci
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        IMAGE_REPO: pavejs/pavejs.org-ci
    steps:
    - name: Checkout
      run: |
        checkout
    - name: Build and push
      run: |
        docker-login
        docker-build-and-push --build-arg VERSION=$GITHUB_SHA .
    - name: Test
      run: |
        docker-compose --file ci/docker-compose.yaml run --rm test